// RUN: mlir-translate --import-dxsa-hex %s | FileCheck %s
// RUN: mlir-translate --import-dxsa-hex %s | mlir-opt --verify-roundtrip
// RUN: mlir-translate --import-dxsa-hex %s 2>&1 | FileCheck %s --check-prefix=DIAG

// CHECK:      dxsa.module {

// CHECK-NEXT:   dxsa.dcl_temps 1
0x02000068, 0x00000001

// Unknown opcode 0x7FF with a valid length of 3.
// CHECK-NEXT:   dxsa.unknown <tokens = [0x030007FF, 0xDEADBEEF, 0x12345678]>
// DIAG: warning: treating next 3 token(s) as unknown: unknown opcode: 2047
0x030007FF, 0xDEADBEEF, 0x12345678

// CHECK-NEXT:   dxsa.dcl_temps 2
0x02000068, 0x00000002

// CUSTOMDATA: the total token count lives in the second token.
// CHECK-NEXT:   dxsa.unknown <tokens = [0x00000035, 0x00000004, 0x11111111, 0x22222222]>
// DIAG: warning: treating next 4 token(s) as unknown: customdata is not supported yet
0x00000035, 0x00000004, 0x11111111, 0x22222222

// CHECK-NEXT:   dxsa.dcl_temps 3
0x02000068, 0x00000003

// Valid D3D10_SB_OPCODE_DCL_TEMPS opcode, but the length is 3 instead of 2.
// CHECK-NEXT:   dxsa.unknown <tokens = [0x03000068, 0x00000005, 0xCAFEBABE]>
// DIAG: warning: treating next 3 token(s) as unknown: instruction length mismatch
0x03000068, 0x00000005, 0xCAFEBABE

// CHECK-NEXT:   dxsa.dcl_temps 4
0x02000068, 0x00000004

// add r0.xyzw, <src0>, r2.xyzw with the src0 operand type field corrupted to
// an unknown value (0xFF).
// CHECK-NEXT:   dxsa.unknown <tokens = [0x07000000, 0x001000F2, 0x00000000, 0x001FFE46, 0x00000001, 0x00100E46, 0x00000002]>
// DIAG: warning: treating next 7 token(s) as unknown: unknown operand type: 255
0x07000000, 0x001000F2, 0x00000000, 0x001FFE46, 0x00000001, 0x00100E46, 0x00000002

// CHECK-NEXT:   dxsa.dcl_temps 5
0x02000068, 0x00000005

// CHECK-NEXT: }
